### ISSUE TITLE
Why not using a backend plugin

### ISSUE THREAD

**Issue by jamuhl** [kingatlas/react-i18next-ondemand#1]
Hi there, here is Jan (jamuhl) maintainer of i18next, react-i18next.

Just wondering why you did this...or honestly might just not understand what it does...why not just using one of the backends...the translate hoc asserts translations get loaded before showing the rendered content already?!?

**Comment by jamuhl** [comment]
ah...think i see it. You like to load an array of keys not a pre specified file.

**Comment by kingatlas** [comment]
As you mentionned, backend plugin does not load translations on demand, but he load by namespace.

**Comment by jamuhl** [comment]
loads on demand - but per namespace ;)

but now i understand your use case for this module...so...looks great - diversity helps the community. So thanks for sharing.

**Comment by jamuhl** [comment]
by the way if you like make a PR to https://www.i18next.com/supported-frameworks.html with your module added.

**Comment by kingatlas** [comment]
Hi @jamuhl, I'm splitting the logic of fetching the missing keys in a separate plugin (https://github.com/kingatlas/i18next-keys-ondemand). The remaining advantage of react-i18next-ondemand component will be to set its state only if its children are concerned by the new translated keys (onI18nChanged event)
